version: '3'
services:
  #PHP Service
  app:
    build: ./back-end/laravel-app
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./back-end/laravel-app:/var/www
      - ./back-end/laravel-app/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  backend:
    image: nginx:alpine
    container_name: backend
    restart: unless-stopped
    tty: true
    volumes:
      - ./back-end/laravel-app:/var/www
      - ./back-end/laravel-app/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    expose:
      - "80"

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: testtest
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./back-end/laravel-app/mysql/my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./front-end/address-book
    volumes:
      - ./front-end/address-book:/app
      - /app/node_modules
    networks:
      - app-network
    expose:
      - "80"

#Proxy service
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./proxy/default.conf:/etc/nginx/nginx.conf
#      - ./proxy/error.log/:/etc/nginx/error_log.log
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local